### ISSUE TITLE
Reverse azimuth is wrong?

### ISSUE THREAD

**Issue by ThomasG77** [axiom-data-science/pygc#2]
Reusing your example with a minor change (end_longitude change from -74 to -73),

```
from pygc import great_distance
great_distance(start_latitude=30, start_longitude=-74, end_latitude=40, end_longitude=-73)
```
It returns

{'azimuth': 4.4220128638613501,
 'distance': array(1113141.5462297963),
 'reverse_azimuth': 184.99779661220958}

I'm not sure the result is normal IMO?
Reverse azimuth (called also Back Azimuth) minus azimuth is not equal to 180 degrees whereas it should (184.99779661220958 - 4.4220128638613501 != 180)

I'm wrong?

**Comment by kwilcox** [comment]
Your assumption is not true for all great circle calculations. It is always true for [rhumb line](https://en.wikipedia.org/wiki/Rhumb_line) calculations (I had to look this up).
