### ISSUE TITLE
`great_distance` can break down for some start/end points

### ISSUE THREAD

**Issue by acrosby** [axiom-data-science/pygc#4]
We ran into this recently. Gets stuck in the lembda loop. Not sure if it is because of the points being roughly on the opposite ends of the globe--maybe precision problem for the angles in radians or some deficiency in the algorithm itself. We can usually perturb the end point a little bit and eventually convergence, but this is not ideal.

If I get time I might dig into it and submit a PR, but take a look and see if you can see whats going on if you get a moment. 

```python
gd = great_distance(start_latitude=52.11, start_longitude=312.44,
                    end_latitude=-52.31, end_longitude=132.54)
```

**Comment by acrosby** [comment]
Apparently this is a known defect in the algorithm https://github.com/JuliaGeo/Geodesy.jl/issues/40

**Comment by kwilcox** [comment]
Interesting. I'll implement a max loop parameter with a sane default of a few hundred to avoid the infinite loop.

**Comment by htyeim** [comment]
Hi, I encountered the same problem:
`pygc.great_distance(start_latitude=35.0,start_longitude=110.0,end_latitude=-35.18,end_longitude=290.19)`

I added the following sentences start from 176 line of gc.py:

```
    max_loop = 66
    count_loop = 0
    while (last_lembda < -3000000.0 or lembda != 0 and np.absolute((last_lembda - lembda) / lembda) > 1.0e-9):
        if count_loop>max_loop:
            print("max loop reached, break")
            break
        count_loop += 1
```
